### ISSUE TITLE
py3.7 is failing CI tests

### ISSUE THREAD

**Issue by mnlevy1981** [marbl-ecosys/feisty#53]
CI has been failing since June 14th, and it's only the python 3.7 matrix. Sample error:

```
 ImportError while importing test module '/home/runner/work/feisty/feisty/tests/test_core.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../micromamba-root/envs/dev-feisty/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_core.py:4: in <module>
    import feisty
feisty/__init__.py:10: in <module>
    from . import offline_driver as offline_driver_mod, testcase
feisty/offline_driver.py:7: in <module>
    import xarray as xr
../../../micromamba-root/envs/dev-feisty/lib/python3.7/site-packages/xarray/__init__.py:1: in <module>
    from . import testing, tutorial, ufuncs
../../../micromamba-root/envs/dev-feisty/lib/python3.7/site-packages/xarray/tutorial.py:13: in <module>
    from .backends.api import open_dataset as _open_dataset
../../../micromamba-root/envs/dev-feisty/lib/python3.7/site-packages/xarray/backends/__init__.py:17: in <module>
    from .zarr import ZarrStore
../../../micromamba-root/envs/dev-feisty/lib/python3.7/site-packages/xarray/backends/zarr.py:22: in <module>
    import zarr
../../../micromamba-root/envs/dev-feisty/lib/python3.7/site-packages/zarr/__init__.py:3: in <module>
    from zarr.convenience import (consolidate_metadata, copy, copy_all, copy_store,
../../../micromamba-root/envs/dev-feisty/lib/python3.7/site-packages/zarr/convenience.py:8: in <module>
    from zarr._storage.store import data_root, meta_root, assert_zarr_v3_api_available
../../../micromamba-root/envs/dev-feisty/lib/python3.7/site-packages/zarr/_storage/store.py:11: in <module>
    from zarr.context import Context
../../../micromamba-root/envs/dev-feisty/lib/python3.7/site-packages/zarr/context.py:2: in <module>
    from typing import TypedDict
E   ImportError: cannot import name 'TypedDict' from 'typing' (/home/runner/micromamba-root/envs/dev-feisty/lib/python3.7/typing.py)
```

Easy "fix" would be to just drop support for 3.7, though I'd like to understand what part of our environment got updated and broken in mid-June...

**Comment by mnlevy1981** [comment]
Reading through the stack, and comparing the [last successful test](https://github.com/mnlevy1981/feisty/actions/runs/5262081617/jobs/9510914715) to the [first failed test](https://github.com/mnlevy1981/feisty/actions/runs/5273817796/jobs/9537661662), it looks like the issue was introduced when `zarr` was updated from `2.14.2` to `2.15.0`. If there was a good way to pin `zarr` only for py3.7, we'd probably be in good shape...

**Comment by klindsay28** [comment]
I encountered the same failure in ci testing of some of my code as well, such as [github.com/klindsay28/esm_catalog_utils](https://github.com/klindsay28/esm_catalog_utils).
The package `zipp` dropped support for py3.7 in version 3.16.0.
In my testing, I pinned `zipp<3.16.0` for py3.7, and this resolved my ci fails.
In order to do this, I have a separate yaml file for py3.7, and include this pin in that yaml file,
and use that yaml file conditionally in my ci.yaml file.
You can look at my esm_catalog_utils repo for details.

As an aside, more and more python packages are dropping support for py3.7,
as support for it has ceased, as of 2023-06-27 (https://devguide.python.org/versions/).
I'm seeing some packages also drop support for py3.8,
as the numpy world has dropped support for py3.8, as of Apr 14, 2023
https://numpy.org/neps/nep-0029-deprecation_policy.html.

**Comment by klindsay28** [comment]
I also pinned `zarr<2.15.0` in py3.7.

**Comment by mnlevy1981** [comment]
I did a brief test where I tried to introduce a step that downgraded `zipp` and `zarr` if python version was 3.7, but it didn't work... it looks github actions lets you skip jobs based on logical tests but not individual steps in a job. Given your comment about py3.7 no longer being supported (and many packages dropping support for it), I think we're justified to drop 3.7 from our testing. To make up for it, we can start testing 3.10 and 3.11 :)

**Comment by mnlevy1981** [comment]
Adding

```yaml
      - name: Use old versions of packages where conda is out of sync with version support
        run: |
          if [[ ${{ matrix.python-version }} == 3.7 ]] ;
          then
            echo "Need to use older versions of zipp and zarr"
            micromamba install zarr=2.14.2 zipp=3.15.0
          else
            echo "Not modifying conda environment"
          fi
```

let me add 3.7 back into test matrix
